### ISSUE TITLE
tonapi.blockchain.send_message(data) Always Returns False

### ISSUE THREAD

**Issue by v1p3rrrrr** [tonkeeper/pytonapi#19]
When calling the send_message function from tonapi.blockchain with the provided data, the transaction_result always returns False, regardless of the actual outcome of the transaction. This behavior is observed whether the transaction was successful or an error occurred.

```
        query = wallet.create_transfer_message(
            to_addr=destination_address,
            amount=transfer_amount,
            payload=payload,
            seqno=seqno,
        )

        message_boc = bytes_to_b64str(query["message"].to_boc(False))

        data = {'boc': message_boc}
        transaction_result = await tonapi.blockchain.send_message(data)
        print(transaction_result)
```

**Comment by nessshon** [comment]
@v1p3rrrrr The `send_message` method in TON API typically doesn't return the transaction result directly. If transaction_result is always False, it might be because the method doesn't provide transaction status in its response. 

Visit https://tonapi.io/api-v2 for more details and documentation on available methods and their return values.
